title: Dystopie v knižní tvorbě
baseURL: http://472622.github.io/hugo-start/
languageCode: cs-cz
publishDir: docs

menu:
  main:
    - name: Domovská stránka
      url: /
      weight: 10
    - name: Novinky
      identifier: post
      url: /post/
      weight: 20
      name: About
      identifier: post
      url: /about/
      weight: 20

params:
  description: Dystopický žánr.
  authors: Authors

