title: Dystopie v knižní tvorbě
baseURL: http://472622.github.io/hugo-start/
languageCode: cs-cz
publishDir: docs

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20
        - name: O projektu
      identifier: post
      url: /post/
      weight: 20

params:
  description: Web o žánru dystopie v knižní tvorbě.
  authors: Authors

